In [1]:
import numpy as np

In [2]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
a.shape

(3, 3)

In [5]:
a.ndim

2

In [6]:
#indexing and slicing can be done using 
#1 double bracket notation a[x][y]
#2 Single bracket notation a[x,y]

In [7]:
#Syntax a[row range,column range]

In [14]:
a[:3] # start from zero to 3rd

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
a[:2] Start from zero to second row i,.e 0,1

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
a[1:2]#sart from 1st row go till second 

array([[4, 5, 6]])

In [20]:
a[0:3] #start from zero go till 3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
a[0:2,0:2] # slice both rows and columnstart at zero go till 2 

array([[1, 2],
       [4, 5]])

In [26]:
b=np.array([[1,2,3,4,5,6],[11,22,33,44,55,66],[111,222,333,444,555,666]])

In [27]:
b

array([[  1,   2,   3,   4,   5,   6],
       [ 11,  22,  33,  44,  55,  66],
       [111, 222, 333, 444, 555, 666]])

In [30]:
b[1:2,3:5]

array([[44, 55]])

In [35]:
np.random.seed(111)

In [48]:
arr=np.random.randint(1,500,30).reshape(6,5)

In [50]:
arr

array([[ 56, 270,  60, 149, 349],
       [228, 217, 446, 213, 405],
       [ 57, 253, 135, 214,  77],
       [115, 133, 428, 115, 254],
       [125, 143, 425, 226, 180],
       [ 39, 357, 166,  62,  22]])

In [53]:
arr[2:,1:]

array([[253, 135, 214,  77],
       [133, 428, 115, 254],
       [143, 425, 226, 180],
       [357, 166,  62,  22]])

In [55]:
arr[2:4,1:3] # start at 2nd row and print 4 from begin i.e.2 here 

array([[253, 135],
       [133, 428]])

In [58]:
arr[5:,4:]   #Get e last element

array([[22]])

In [59]:
arr[5:,3:4]  # get e second last element

array([[62]])