# Slicing can be done as a view or copy

In [1]:
# In view - it make changes to existing array while in copy you copy it to new array where changes are reflected 

In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3,4,5,6,7,8,9])

In [4]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
slicing=a[3:5]

In [6]:
slicing

array([4, 5])

In [7]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
slicing[:]=0

In [9]:
a

array([1, 2, 3, 0, 0, 6, 7, 8, 9])

In [24]:
slicing=a[7:9] # here we created a view ofgiven element 

In [25]:
 slicing[:]=5  # on above view we did a update , it gets reflected to original array also

In [26]:
a # so here we see that elements in a are getting updated 

array([1, 2, 3, 0, 0, 6, 7, 5, 5])

In [27]:
slicing=a[1:6].copy()  # here we are creating copy of the element

In [28]:
slicing[:]=9

In [29]:
slicing

array([9, 9, 9, 9, 9])

In [30]:
a # original array is unchanged

array([1, 2, 3, 0, 0, 6, 7, 5, 5])