In [2]:
import numpy as np

In [3]:
arr=np.arange(30)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [10]:
arr>3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [11]:
arr[arr>3]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
       21, 22, 23, 24, 25, 26, 27, 28, 29])

In [13]:
b=arr[arr<2]

In [14]:
b

array([0, 1])

In [15]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [19]:
arr[arr==7]

array([7])

In [21]:
arr[arr%3==0]

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [22]:
#We can update the element alsowhere condition matches
arr[arr<3]=0

In [23]:
arr

array([ 0,  0,  0,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [30]:
arr1=arr[arr<3].copy()

In [31]:
arr1

array([0, 0, 0])

In [32]:
arr1[arr1<5]=5

In [33]:
arr1

array([5, 5, 5])