In [1]:
# we can perform mathemtical or logical operations on numpy arrays

In [3]:
import numpy as np
a=np.arange(25,43)
a

array([25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
       42])

In [4]:
a=a*2

In [5]:
a

array([50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82,
       84])

In [6]:
a=a+1

In [7]:
a

array([51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83,
       85])

In [10]:
b=np.arange(25,43)

In [11]:
a=a*b

In [12]:
a

array([1275, 1378, 1485, 1596, 1711, 1830, 1953, 2080, 2211, 2346, 2485,
       2628, 2775, 2926, 3081, 3240, 3403, 3570])

In [13]:
a=a/b

In [14]:
a

array([51., 53., 55., 57., 59., 61., 63., 65., 67., 69., 71., 73., 75.,
       77., 79., 81., 83., 85.])

In [23]:
b=np.array([2,8])

In [24]:
b

array([2, 8])

In [25]:
b**2

array([ 4, 64], dtype=int32)

In [26]:
#same way we can operate on 2*2 array

In [31]:
arr=np.arange(4).reshape(2,2)
arr1=np.arange(4).reshape(2,2)
                        

In [32]:
arr

array([[0, 1],
       [2, 3]])

In [33]:
arr1

array([[0, 1],
       [2, 3]])

In [34]:
arr=arr*arr1

In [35]:
arr

array([[0, 1],
       [4, 9]])

In [36]:
arr=arr-arr1

In [37]:
arr

array([[0, 0],
       [2, 6]])

In [38]:
arr1

array([[0, 1],
       [2, 3]])

In [40]:
#IF we want dot product then use --This is multiplicationof 2 metrix 
arr.dot(arr1)

array([[ 0,  0],
       [12, 20]])