In [1]:
#Function zero -- assign value zero to array we are intitalizing (irrespecive its one dim or two dim)


In [2]:
import numpy as np
a=np.zeros(5)

In [3]:
a

array([0., 0., 0., 0., 0.])

In [4]:
twodim=np.zeros([2,2])

In [5]:
twodim

array([[0., 0.],
       [0., 0.]])

In [6]:
twodim=np.zeros([2,3])

In [7]:
twodim

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
treedim=np.zeros([3,2,1])

In [10]:
treedim

array([[[0.],
        [0.]],

       [[0.],
        [0.]],

       [[0.],
        [0.]]])

In [11]:
onesarray=np.ones(4)

In [17]:
onesarray

array([1., 1., 1., 1.])

# EYE function - creates array with all diagonal ele as 1 

In [13]:
arr=np.eye(3)

In [14]:
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
arr=np.eye(2)

In [16]:
arr

array([[1., 0.],
       [0., 1.]])

In [17]:
arr=np.eye(1)

In [18]:
arr

array([[1.]])

In [19]:
arr=np.eye(2,3)

In [29]:
arr

array([[1., 0., 0.],
       [0., 1., 0.]])

# diag functions gives defined values to diagonal elements 

In [20]:
arr=np.diag([1,5,9])

In [6]:
arr

array([[1, 0, 0],
       [0, 5, 0],
       [0, 0, 9]])

In [32]:
#read onlydiagonalelements

In [21]:
np.diag(arr)

array([1, 5, 9])

In [22]:
arr

array([[1, 0, 0],
       [0, 5, 0],
       [0, 0, 9]])

# randint - generate random number between start and end 

In [26]:
arr=np.random.randint(1,10,3)

In [27]:
arr

array([7, 6, 7])

In [30]:
import numpy as np #without range
arr=np.random.rand(3)

In [31]:
arr

array([0.3941899, 0.6559665, 0.8548218])

In [32]:
arr=np.random.rand(2,2)

In [33]:
arr

array([[0.63710773, 0.47157422],
       [0.4356656 , 0.94971928]])

# randn - generate random number close to zero

In [34]:
arr=np.random.randn(10)

In [35]:
arr

array([-1.59448313,  0.81412123, -1.05773752, -0.59057082, -0.01075588,
       -0.48653451,  0.36599944, -1.58002818,  1.16516322,  0.73287084])

# Some other list of array functions

In [11]:
arr=np.array([10,40,11,23,50,65,57])

In [36]:
np.sort(arr)

array([-1.59448313, -1.58002818, -1.05773752, -0.59057082, -0.48653451,
       -0.01075588,  0.36599944,  0.73287084,  0.81412123,  1.16516322])

In [37]:
np.min(arr)

-1.5944831294060111

In [14]:
np.max(arr)

65

In [38]:
np.argmin(arr)

0

In [39]:
np.argmax(arr)

8

In [40]:
np.sqrt(arr)

C:\Users\swapnil\AppData\Local\Temp\ipykernel_7744\2296558006.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr)


array([       nan, 0.90228667,        nan,        nan,        nan,
              nan, 0.60497888,        nan, 1.07942727, 0.85607876])

In [42]:
np.sin(arr)
np.cos(arr)

array([-0.02368459,  0.68650763,  0.49084451,  0.83062296,  0.99994216,
        0.88395851,  0.93376654, -0.00923172,  0.39460057,  0.74325686])

In [43]:
ar=np.array([1,5,10,15])

In [44]:
np.linspace(0,20,5)  # it returns 5 numbers with equal diff between 0 and 20 

array([ 0.,  5., 10., 15., 20.])

In [32]:
# working iwth 2darray
np.random.seed(122)

In [46]:
twod=np.random.randint(1,21,9).reshape(3,3)

In [47]:
twod

array([[ 2, 11, 17],
       [11,  9, 20],
       [20, 19, 19]])

In [35]:
np.sum(twod)

116

In [38]:
np.max(twod),np.min(twod)

(17, 3)

In [39]:
twod.max()

17

In [40]:
np.sum(twod,axis=0)

array([36, 40, 40])

In [41]:
np.min(twod,axis=1)

array([11, 13,  3])

In [42]:
#So axis = 1 represent row axis=0 represent column 

In [48]:
#cumulative sum
np.cumsum(twod)

array([  2,  13,  30,  41,  50,  70,  90, 109, 128], dtype=int32)

In [49]:
np.random.shuffle(twod) # shuffle the elements - change the position

In [50]:
twod

array([[11,  9, 20],
       [20, 19, 19],
       [ 2, 11, 17]])

In [51]:
np.unique(twod)

array([ 2,  9, 11, 17, 19, 20])

In [52]:
np.unique(twod).size

6

In [58]:
# returns unique elements , position of first occ of element, number of times element repeated
np.unique(twod,return_index=True,return_counts=True) 

(array([ 3, 11, 13, 16, 17]),
 array([3, 1, 2, 0, 6], dtype=int64),
 array([1, 2, 2, 3, 1], dtype=int64))

In [1]:
#filter
import numpy as np

arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [3]:
import numpy as np

arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(element)
  
newarr = filter_arr

print(filter_arr)
print(newarr)

[43, 44]
[43, 44]
