In [1]:
# Two types of stacking -
#Horizontal
#Vertical

In [2]:
import numpy as np

In [4]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])

In [5]:
arr1

array([1, 2, 3, 4, 5])

In [6]:
arr2

array([ 6,  7,  8,  9, 10])

In [7]:
np.hstack([arr1,arr2])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
np.vstack([arr1,arr2])

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [9]:
arr3=np.vstack([arr1,arr2])

In [10]:
arr3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [11]:
#stacking 2D array
arr1=np.random.randint(1,20,9).reshape(3,3)
arr2=np.random.randint(1,20,9).reshape(3,3)

In [12]:
arr1

array([[16, 14, 16],
       [17,  9,  3],
       [ 2,  8,  4]])

In [13]:
arr2

array([[ 6, 12, 14],
       [16,  5, 14],
       [ 2, 19,  9]])

In [14]:
np.hstack([arr1,arr2])

array([[16, 14, 16,  6, 12, 14],
       [17,  9,  3, 16,  5, 14],
       [ 2,  8,  4,  2, 19,  9]])

In [15]:
np.vstack([arr1,arr2])

array([[16, 14, 16],
       [17,  9,  3],
       [ 2,  8,  4],
       [ 6, 12, 14],
       [16,  5, 14],
       [ 2, 19,  9]])

In [21]:
%timeit 2+3

20.4 ns ± 4.08 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
