In [1]:
import numpy as np

In [2]:
data=np.loadtxt("D:\Swapnil-D drive\Study\Python\Python_NumPy_dataset\even_no.txt")

In [3]:
print(data)

[[ 2.  4.  6.  8. 10.]
 [12. 14. 16. 18. 20.]
 [22. 24. 26. 28. 30.]
 [32. 34. 36. 38. 40.]
 [42. 44. 46. 48. 50.]]


In [4]:
print(type(data))

<class 'numpy.ndarray'>


In [5]:
data.dtype

dtype('float64')

In [12]:
#convertto in 
data=np.loadtxt("D:\Swapnil-D drive\Study\Python\Python_NumPy_dataset\even_no.txt",dtype=int,skiprows=0,usecols=(1,3))
#use skip row to skip the header

In [13]:
print(data)

[[ 4  8]
 [14 18]
 [24 28]
 [34 38]
 [44 48]]


In [14]:
data=np.loadtxt("D:\Swapnil-D drive\Study\Python\Python_NumPy_dataset\even_no.txt",dtype=int,skiprows=0,usecols=(0))

In [15]:
data

array([ 2, 12, 22, 32, 42])

In [19]:
# ifwe want in string form
data=np.loadtxt("D:\Swapnil-D drive\Study\Python\Python_NumPy_dataset\even_no.txt",dtype=str,usecols=(0))

In [20]:
data

array(['2', '12', '22', '32', '42'], dtype='<U2')

In [29]:
#Laod csv file
datacsv=np.loadtxt("D:\Swapnil-D drive\Study\Python\Python_NumPy_dataset\data_csv.csv",delimiter=',')

In [27]:
datacsv

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 2., 21., 23., 24., 25.],
       [ 3., 31., 32., 33., 34.],
       [ 4., 41., 42., 43., 44.]])

In [31]:
datacsv.shape # size of array

(4, 5)

In [32]:
#Assume first column is id and we dont want it 
datacsv[:,1:]

array([[ 2.,  3.,  4.,  5.],
       [21., 23., 24., 25.],
       [31., 32., 33., 34.],
       [41., 42., 43., 44.]])

In [35]:
#when we have nullvalues indata set 
datacsv=np.loadtxt("D:\Swapnil-D drive\Study\Python\Python_NumPy_dataset\data_csv_with_null.csv",delimiter=',')

In [36]:
datacsv #Null values are replaced with zeros

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 2., 21., 23.,  0., 25.],
       [ 3., 31.,  0., 33., 34.],
       [ 4., 41., 42.,  0.,  0.]])

In [49]:

datacsv=np.genfromtxt("D:\Swapnil-D drive\Study\Python\Python_NumPy_dataset\data_csv_with_null.csv",delimiter=',')

In [50]:
datacsv  #here u can see null values are shown as nan

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 2., 21., 23., nan, 25.],
       [ 3., 31., nan, 33., 34.],
       [ 4., 41., 42., nan, nan]])

In [51]:
datacsv=np.genfromtxt("D:\Swapnil-D drive\Study\Python\Python_NumPy_dataset\data_csv_with_null.csv",delimiter=',', filling_values=10)

In [54]:
 # we can fill he missing values as mentioned above 
datacsv

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 2., 21., 23., 10., 25.],
       [ 3., 31., 10., 33., 34.],
       [ 4., 41., 42., 10., 10.]])

In [60]:
#user can mention missingvalues as a ? which you want to replace it with zero
datacsv=np.genfromtxt("D:\Swapnil-D drive\Study\Python\Python_NumPy_dataset\data_csv_with_null_1.csv",delimiter=',', missing_values='?',filling_values=10)

In [61]:
datacsv

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 2., 21., 23., 24., 25.],
       [ 3., 31., 32., 33., 34.],
       [ 4., 41., 42., 10., 10.]])

In [62]:
#so null as wellas missing values are replaced with 10
#missing_values work with int only 

In [63]:
##############Types of files Pthon handles - Binary or Text 
## Binary files are oher than txt like video , image etc
#File operations - CRUD (Create,read,update,delete) and others like copy share etc


In [65]:
# OPenfile - open(filename,mode)
# mode -Read,append,wirte,correct , if it doesnot exists then it creates the file

In [66]:
dopen= open("D:\Swapnil-D drive\Study\Python\Python_NumPy_dataset\data_csv.csv")

In [67]:
dopen

<_io.TextIOWrapper name='D:\\Swapnil-D drive\\Study\\Python\\Python_NumPy_dataset\\data_csv.csv' mode='r' encoding='cp1252'>

In [68]:
print(dopen.read())

1,2,3,4,5
2,21,23,24,25
3,31,32,33,34
4,41,42,43,44



In [77]:
dopen= open("D:\Swapnil-D drive\Study\Python\Python_NumPy_dataset\data_csv.csv")
print (dopen.read(20)) # read first 20 chars

1,2,3,4,5
2,21,23,24


In [78]:
dopen.close()

In [79]:
dopen

<_io.TextIOWrapper name='D:\\Swapnil-D drive\\Study\\Python\\Python_NumPy_dataset\\data_csv.csv' mode='r' encoding='cp1252'>

In [81]:
print(dopen.readlines())

ValueError: I/O operation on closed file.

In [92]:
dopen= open("D:\Swapnil-D drive\Study\Python\Python_NumPy_dataset\data_csv.csv")

In [93]:
print(dopen.readlines())

['1,2,3,4,5\n', '2,21,23,24,25\n', '3,31,32,33,34\n', '4,41,42,43,44\n']


In [100]:
dopen= open("D:\Swapnil-D drive\Study\Python\Python_NumPy_dataset\data_csv.csv")
print(dopen.readlines(10))
print(dopen.readline(10))

['1,2,3,4,5\n', '2,21,23,24,25\n']
3,31,32,33


In [101]:
dopen= open("D:\Swapnil-D drive\Study\Python\Python_NumPy_dataset\data_csv.csv")
for line in dopen:
    print(dopen.readline())

2,21,23,24,25

4,41,42,43,44



In [107]:
dopen=open("D:\Swapnil-D drive\Study\Python\Python_NumPy_dataset\data_write_append.txt",'w')

In [108]:
dopen.write("This is my first line")

21

In [109]:
dopen.close()

In [114]:
dopen=open("D:\Swapnil-D drive\Study\Python\Python_NumPy_dataset\data_write_append.txt",'w')

In [115]:
dopen.write("Hello world")
dopen.close() ## This will overrride , what if we want to append

In [125]:
dopen=open("D:\Swapnil-D drive\Study\Python\Python_NumPy_dataset\data_write_append.txt",'a')

In [126]:
dopen.write(" Append this text ")

18

In [127]:
dopen.close()

In [128]:
dopen=open("D:\Swapnil-D drive\Study\Python\Python_NumPy_dataset\data_write_append.txt",'a')

In [129]:
dopen.write("writing to ile")

14

In [131]:
dopen.close()

In [132]:
#creating a new file 
dopen=open("D:\Swapnil-D drive\Study\Python\Python_NumPy_dataset\data_newFile.txt",'x')


In [136]:
dopen.write("Hi") # if u try to create same file again, file exists error will occur

ValueError: I/O operation on closed file.

In [135]:
dopen.close()

In [137]:
#deleting a file
import os
os.remove("D:\Swapnil-D drive\Study\Python\Python_NumPy_dataset\data_newFile.txt")

In [138]:
#validate before delete

In [142]:
import os 
if os.path.exists("D:\Swapnil-D drive\Study\Python\Python_NumPy_dataset\even_no.txt"):
    print("file exists--------")
    os.remove("D:\Swapnil-D drive\Study\Python\Python_NumPy_dataset\even_no.txt")
else:
    print("File does not exists")

file exists--------


In [143]:
import os 
if os.path.exists("D:\Swapnil-D drive\Study\Python\Python_NumPy_dataset\even_no.txt"):
    print("file exists--------")
    os.remove("D:\Swapnil-D drive\Study\Python\Python_NumPy_dataset\even_no.txt")
else:
    print("File does not exists")

File does not exists
