# Converting 1 dim to 2 dim or v/s or similar conversions

In [1]:
import numpy as np

In [2]:
# crate one dim array
arr=np.random.randint(1,50,12)

In [3]:
arr

array([43, 20, 48,  6, 24, 41,  7,  2, 31,  4, 40, 25])

In [4]:
arr.shape

(12,)

In [5]:
arr.ndim

1

In [11]:
arr=arr.reshape(2,6) # 2 rows 6 coulms

In [8]:
arr

array([[43, 20, 48,  6, 24, 41],
       [ 7,  2, 31,  4, 40, 25]])

In [12]:
arr=arr.reshape(1,12)

In [13]:
arr

array([[43, 20, 48,  6, 24, 41,  7,  2, 31,  4, 40, 25]])

In [14]:
arr=arr.reshape(2,6) # 2 rows 6 coulms

In [15]:
arr

array([[43, 20, 48,  6, 24, 41],
       [ 7,  2, 31,  4, 40, 25]])

In [16]:
arr=arr.reshape(3,4)

In [17]:
arr

array([[43, 20, 48,  6],
       [24, 41,  7,  2],
       [31,  4, 40, 25]])

In [18]:
arr=arr.reshape(6,2)

In [19]:
arr

array([[43, 20],
       [48,  6],
       [24, 41],
       [ 7,  2],
       [31,  4],
       [40, 25]])

In [20]:
arr=arr.reshape(12) # 1 dim

In [21]:
arr

array([43, 20, 48,  6, 24, 41,  7,  2, 31,  4, 40, 25])

In [22]:
arr=arr.reshape(2,2,3) # 3 dim array

In [23]:
arr

array([[[43, 20, 48],
        [ 6, 24, 41]],

       [[ 7,  2, 31],
        [ 4, 40, 25]]])

In [24]:
arr.ndim

3

In [25]:
a=arr

In [26]:
a

array([[[43, 20, 48],
        [ 6, 24, 41]],

       [[ 7,  2, 31],
        [ 4, 40, 25]]])

In [27]:
a=a.reshape(2,-1)# convert to 2D array -1 says system to calculate size of column

In [28]:
a

array([[43, 20, 48,  6, 24, 41],
       [ 7,  2, 31,  4, 40, 25]])

In [30]:
a=a.reshape(-1,4)# convert to 2D array -1 says system to calculate size of rows

In [31]:
a

array([[43, 20, 48,  6],
       [24, 41,  7,  2],
       [31,  4, 40, 25]])

In [32]:
a.shape

(3, 4)