# Excercise

In [1]:
import math

In [4]:
a=10
math.pow(a,2)

100.0

In [5]:
mylst="Hi how are you"

In [6]:
mylst.split()[3]

'you'

In [9]:
mylst=[1,2,3,["hi","bye"],True,[False,True,"Hi"]]

In [12]:
print(mylst)

[1, 2, 3, ['hi', 'bye'], True, [False, True, 'Hi']]


In [17]:
print(mylst[3][1])

bye


In [18]:
print(mylst[3][0])

hi


In [19]:
print(mylst[5][1])

True


In [20]:
mylst=[1,2,3,["hi","bye",["111","222"]],True,[False,True,"Hi"]]

In [21]:
print(mylst[3][2][1])

222


In [23]:
#remove last element
mylst.pop()

[False, True, 'Hi']

In [24]:
print(mylst)

[1, 2, 3, ['hi', 'bye', ['111', '222']], True]


In [36]:
#remove 3 element again
mylst.remove(3)

ValueError: list.remove(x): x not in list

In [37]:
print(mylst)

[2, ['hi', 'bye', ['111', '222']], True]


#Calcualte day number  when your  birthday . ex. - input 1st Feb: return32
#birthday and birthmonthwill be an input 


In [51]:
def calbirthday(month,day):
    days = [31,28,30,31,30,31,30,31,30,31,30,31]
    summonths=0
    if day>31:
        print("Invalid birthdate")
        return 0
    if month>11:
        print("Invalid wrongmonth")
        return 0
    if month==0:
         return day
    else:
        return int(sum(days[:month]))+day
    
    

In [57]:
calbirthday(11,31)

364

In [58]:
mydict={"first":[23,14,12],"second":[23,3,34]}

In [59]:
mydict["second"]

[23, 3, 34]

In [60]:
mydict["second"][1]

3

In [61]:
import numpy as np

In [76]:
d=np.linspace(0,10,5)

In [77]:
print(d)

[ 0.   2.5  5.   7.5 10. ]


In [79]:
a=np.array([1,2,3])
b=np.array([1,3,3])

In [80]:
b==a

array([ True, False,  True])

In [82]:
b[1]==a[1]

True

In [83]:
b[1]=4

In [84]:
b[1]==a[1]

False

In [85]:
a.sum()

6

In [87]:
a[:2].sum()

3

In [89]:
a.sum()

6

In [91]:
a.mean()

2.0

In [94]:
t=np.array((1,2,3,4))

In [96]:
t

array([1, 2, 3, 4])

In [99]:
t.shape

(4,)

In [101]:
t.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [104]:
np.arange(-5,0)

array([-5, -4, -3, -2, -1])