In [1]:
import sys

In [2]:
import numpy as np

In [4]:
a=np.array([1,2,3])

In [5]:
a

array([1, 2, 3])

In [7]:
b=np.arange(10)

In [8]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
print(b)

[0 1 2 3 4 5 6 7 8 9]


In [14]:
#Creating array with inut 
c=[]
n=int(input("Enter size of array"))
for i in range(n):
    val=int(input("ente number--"))
    c.append(val)
print(c)

Enter size of array2
ente number--34
ente number--65
[34, 65]


In [15]:
d=np.array(c)

In [16]:
d

array([34, 65])

In [17]:
#Soabove we converted regular array to numpyarray 

# Two dim array

In [18]:
# if we have 2 opening bracks it means its 2 dim array
a=[[1,2,3],[4,5,6]]

In [19]:
twoa=np.array(a)

In [20]:
twoa

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
print(twoa)

[[1 2 3]
 [4 5 6]]


In [22]:
twoa.ndim

2

In [23]:
twoa.shape

(2, 3)