# Hands on - basic array format in numpy

In [4]:
#Python package for numerical arraycalculations - mathemetical and logical
import sys
import numpy as np

In [9]:
np.array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

In [10]:
a=np.array([1,2,3,4,5,8,7])

In [11]:
print(a)

[1 2 3 4 5 8 7]


In [8]:
print(type(a))

<class 'numpy.ndarray'>


In [7]:
b=np.array([1.2,0.2,3,4])

In [8]:
print(b)

[1.2 0.2 3.  4. ]


In [10]:
print(type(b))

<class 'numpy.ndarray'>


In [11]:
a[0]

1

In [12]:
b[-2]

3.0

In [14]:
b[:2]

array([1.2, 0.2])

# Array types

In [3]:
a=np.array([1,2,3,4])

In [4]:
a

array([1, 2, 3, 4])

In [9]:
# since all elements are integer 
a.dtype

dtype('int32')

In [10]:
a1=np.array([1.2,2,3,4])

In [11]:
# if any of the elemt is float 
a1.dtype

dtype('float64')

In [20]:
# string type 
a2=np.array(['a','b','2'])

In [21]:
a2.dtype

dtype('<U1')

In [23]:
#more than one dime
md=np.array([[1,2],[3,4]])

In [24]:
md

array([[1, 2],
       [3, 4]])

In [25]:
print(md)

[[1 2]
 [3 4]]


In [33]:
# dtype parameter 
import numpy as np 
a = np.array([1, 2, 3], dtype = complex) 
print(a) 

[1.+0.j 2.+0.j 3.+0.j]


In [40]:
#Strucutred data type
import numpy as np 
student = np.dtype([('name','S20'), ('age', 'i1'), ('marks', 'f4')]) 
print(student)

ary = np.array([('abc', 21.2, 50.23),('xyz', 18, 75)], dtype = student) 
print (ary)

[('name', 'S20'), ('age', 'i1'), ('marks', '<f4')]
[(b'abc', 21, 50.23) (b'xyz', 18, 75.  )]


In [42]:
# now apply it to ndarray object 
import numpy as np 

dt = np.dtype([('age',np.int8)]) 
a = np.array([(10),(20,),(30,)], dtype = dt) 
print (a)

[(10,) (20,) (30,)]


# Dimensions and shapes

In [46]:
AS=np.array(
[
    [1,2],
    [5,6],
    [5,4]
])

In [47]:
AS.shape

(3, 2)

In [61]:
# how manydim it has , her its one vertial and one horiz
AS.ndim

2

In [50]:
AS.size

6

In [63]:
as1=np.array([
        [ [12, 11, 10],
            [ 9,  8,  7]
        ],

       [
           [ 6,  5,  4],
           [ 3,  2,  1]]
        ]
)

In [64]:
as1.shape

(2, 2, 3)

In [66]:
as1.ndim

3

# Indexing and Slicing of Matrices

In [67]:
# Square matrix
A = np.array([
#.   0. 1. 2
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8, 9]  # 2
])

In [68]:
A[1]

array([4, 5, 6])

In [69]:
A[1,2]

6

In [73]:
A.size

9

In [74]:
A.ndim

2

In [78]:
A[1:,0:]

array([[4, 5, 6],
       [7, 8, 9]])

In [80]:
A[1:,:2]

array([[4, 5],
       [7, 8]])

In [81]:
A[1][0]

4

In [82]:
A[1:2]

array([[4, 5, 6]])

In [83]:
A[1:2,1:2]

array([[5]])

In [84]:
A[1:2,0:1]

array([[4]])

In [85]:
A[2]

array([7, 8, 9])

In [86]:
A[2]=99

In [87]:
A[2]

array([99, 99, 99])

In [88]:
A[2][0]=00

In [89]:
A[2]

array([ 0, 99, 99])

In [90]:
A1=A

In [91]:
A1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 0, 99, 99]])

In [93]:
A[2]=98

In [99]:
A

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [98, 98, 98]])

In [98]:
A1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [98, 98, 98]])

In [100]:
A[2]=35

In [101]:
A

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [35, 35, 35]])

In [102]:
A1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [35, 35, 35]])

In [105]:
# reesize the array
import numpy as np 
a = np.array([[1,2,3],[4,5,6]]) 
b = a.reshape(3,2) 
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [106]:
# this is one dimensional array 
import numpy as np 
a = np.arange(24) 
a.ndim  


1

# Operations

In [108]:
op=np.arange(4)

In [109]:
op

array([0, 1, 2, 3])

In [110]:
op = op + 10

In [111]:
op

array([10, 11, 12, 13])

In [112]:
op = op* 10

In [113]:
op

array([100, 110, 120, 130])

In [114]:
op.sum

<function ndarray.sum>

In [117]:
help(sum)

Help on built-in function sum in module builtins:

sum(iterable, /, start=0)
    Return the sum of a 'start' value (default: 0) plus an iterable of numbers
    
    When the iterable is empty, return the start value.
    This function is intended specifically for use with numeric values and may
    reject non-numeric types.



In [118]:
op

array([100, 110, 120, 130])

In [119]:
op1=np.array([1,1,1,1])

In [120]:
op+op1

array([101, 111, 121, 131])

In [121]:
op2=op+op1

In [122]:
op2

array([101, 111, 121, 131])

In [123]:
op2.mean()

116.0

In [124]:
op2.sum()

464

In [125]:
op2.max()

131

In [127]:
op2.min()

101

# Boolean arrays

In [4]:
import numpy as np 
a=np.arange(4)

In [5]:
a

array([0, 1, 2, 3])

In [7]:
a[[0,-1]]

array([0, 3])

In [9]:
# boolean arrays
a=[[True,False,False,True]]

In [14]:
a=np.arange(4)

In [15]:
a >=2

array([False, False,  True,  True])

In [16]:
a[a>=2]

array([2, 3])

In [17]:
a.mean()

1.5

In [18]:
a

array([0, 1, 2, 3])

In [20]:
#selecting elemets greater than mean 
a[(a>a.mean())]

array([2, 3])

In [21]:
#logical or operator 
a[(a==1) | (a==3)]

array([1, 3])

In [25]:
#Logical andoperator
a[(a<=3) & (a%2==0)]

array([0, 2])

In [28]:
a1=np.random.randint(100,size=(3,2))

In [29]:
a1

array([[98, 84],
       [ 4, 50],
       [ 7, 17]])

In [31]:
a1[a1>50]

array([98, 84])

In [40]:
import numpy as np
a2=np.arange(5)

In [41]:
a2

array([0, 1, 2, 3, 4])

In [42]:
a2<=3

array([ True,  True,  True,  True, False])

In [43]:
print(a2<=3)

[ True  True  True  True False]


In [44]:
print(a2[a2<=3])

[0 1 2 3]


# Linear algebra

In [49]:
A= np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [51]:
B=np.array([
    [6,5],
    [4,3],
    [2,1]
    ])

In [52]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [2]:
help

Type help() for interactive help, or help(object) for help about object.

# 